name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ["8.4", "8.5"]
        laravel: ["^12.0", "^13.0"]

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Set laravel version
        run: composer require "laravel/framework=${{ matrix.laravel }}" --no-update --no-interaction --no-progress

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Execute pint
        run: vendor/bin/pint --test

      - name: Execute phpstan
        run: vendor/bin/phpstan

      - name: Execute rector
        run: vendor/bin/rector --dry-run

  lints:
    runs-on: ubuntu-latest

    name: Lints

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute pint
        run: vendor/bin/pint --test

      - name: Execute phpstan
        run: vendor/bin/phpstan

      - name: Execute rector
        run: vendor/bin/rector --dry-run
